specVersion: 0.0.6
schema:
  file: ./schema.graphql
{{#graftEnabled}}
description: ...
features:
  - grafting
graft:
  base: {{subgraphId}} # Subgraph ID of base subgraph
  block: {{graftStartBlock}} # Block number
{{/graftEnabled}}
dataSources:
  - kind: ethereum/contract
    name: PoolManagerFactory
    network: {{ network }}
    source:
      address: "{{ poolManager.address }}"
      abi: PoolManagerFactory
      startBlock: {{ poolManager.startBlock }}
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities: []
      abis:
        - name: PoolManagerFactory
          file: ./abis/PoolManagerFactory.json
        - name: PoolManager
          file: ./abis/PoolManager.json
        - name: Pool
          file: ./abis/Pool.json
        - name: ERC20
          file: ./abis/ERC20.json
        - name: ERC20NameBytes
          file: ./abis/ERC20NameBytes.json
        - name: ERC20SymbolBytes
          file: ./abis/ERC20SymbolBytes.json
      eventHandlers:
        - event: InstanceDeployed(indexed uint256,indexed address,bytes)
          handler: handleManagerInstanceDeployed
      file: ./protocols/maple-finance-v2/src/mapping.ts
templates:
  - kind: ethereum/contract
    name: PoolManager
    network: {{ network }}
    source:
      abi: PoolManager
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities: []
      abis:
        - name: PoolManager
          file: ./abis/PoolManager.json
        - name: Pool
          file: ./abis/Pool.json
      eventHandlers:
        - event: SetAsActive(bool)
          handler: handleSetAsActive
      file: ./protocols/maple-finance-v2/src/mapping.ts
