specVersion: 0.0.6
schema:
  file: ./schema.graphql
{{#graftEnabled}}
description: ...
features:
  - grafting
graft:
  base: {{subgraphId}} # Subgraph ID of base subgraph
  block: {{graftStartBlock}} # Block number
{{/graftEnabled}}
dataSources:
  - kind: ethereum/contract
    name: PoolManagerFactory
    network: {{ network }}
    source:
      address: "{{ poolManagerFactory.address }}"
      abi: ContractFactory
      startBlock: {{ poolManagerFactory.startBlock }}
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities: []
      abis:
        - name: ContractFactory
          file: ./abis/ContractFactory.json
        - name: PoolManager
          file: ./abis/PoolManager.json
        - name: Pool
          file: ./abis/Pool.json
        - name: ERC20
          file: ./abis/ERC20.json
        - name: ERC20NameBytes
          file: ./abis/ERC20NameBytes.json
        - name: ERC20SymbolBytes
          file: ./abis/ERC20SymbolBytes.json
      eventHandlers:
        - event: InstanceDeployed(indexed uint256,indexed address,bytes)
          handler: handleManagerInstanceDeployed
      file: ./protocols/maple-finance-v2/src/mapping.ts
  - kind: ethereum/contract
    name: MapleLoanFactory
    network: {{ network }}
    source:
      address: "{{ mapleLoanFactory.address }}"
      abi: ContractFactory
      startBlock: {{ mapleLoanFactory.startBlock }}
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities: []
      abis:
        - name: ContractFactory
          file: ./abis/ContractFactory.json
      eventHandlers:
        - event: InstanceDeployed(indexed uint256,indexed address,bytes)
          handler: handleLoanInstanceDeployed
      file: ./protocols/maple-finance-v2/src/mapping.ts
  - kind: ethereum/contract
    name: WithdrawalManagerFactory
    network: {{ network }}
    source:
      address: "{{ withdrawalManagerFactory.address }}"
      abi: ContractFactory
      startBlock: {{ withdrawalManagerFactory.startBlock }}
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities: []
      abis:
        - name: ContractFactory
          file: ./abis/ContractFactory.json
      eventHandlers:
        - event: InstanceDeployed(indexed uint256,indexed address,bytes)
          handler: handleWithdrawalInstanceDeployed
      file: ./protocols/maple-finance-v2/src/mapping.ts
  - kind: ethereum/contract
    name: LoanManagerFactory
    network: {{ network }}
    source:
      address: "{{ loanManagerFactory.address }}"
      abi: ContractFactory
      startBlock: {{ loanManagerFactory.startBlock }}
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities: []
      abis:
        - name: ContractFactory
          file: ./abis/ContractFactory.json
      eventHandlers:
        - event: InstanceDeployed(indexed uint256,indexed address,bytes)
          handler: handleLoanManagerInstanceDeployed
      file: ./protocols/maple-finance-v2/src/mapping.ts
  - kind: ethereum/contract
    name: LiquidatorFactory
    network: {{ network }}
    source:
      address: "{{ liquidatorFactory.address }}"
      abi: ContractFactory
      startBlock: {{ liquidatorFactory.startBlock }}
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities: []
      abis:
        - name: ContractFactory
          file: ./abis/ContractFactory.json
      eventHandlers:
        - event: InstanceDeployed(indexed uint256,indexed address,bytes)
          handler: handleLiquidatorInstanceDeployed
      file: ./protocols/maple-finance-v2/src/mapping.ts
templates:
  - kind: ethereum/contract
    name: PoolManager
    network: {{ network }}
    source:
      abi: PoolManager
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities: []
      abis:
        - name: PoolManager
          file: ./abis/PoolManager.json
        - name: Pool
          file: ./abis/Pool.json
      eventHandlers:
        - event: SetAsActive(bool)
          handler: handleSetAsActive
      file: ./protocols/maple-finance-v2/src/mapping.ts
  - kind: ethereum/contract
    name: MapleLoan
    network: {{ network }}
    source:
      abi: MapleLoan
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities: []
      abis:
        - name: MapleLoan
          file: ./abis/MapleLoan.json
        - name: MapleGlobals
          file: ./abis/MapleGlobals.json
      eventHandlers:
        - event: Initialized(indexed address,indexed address,address[2],uint256[3],uint256[3],uint256[4],uint256[2])
          handler: handleLoanInitialized
      file: ./protocols/maple-finance-v2/src/mapping.ts
  - kind: ethereum/contract
    name: WithdrawalManager
    network: {{ network }}
    source:
      abi: WithdrawalManager
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities: []
      abis:
        - name: WithdrawalManager
          file: ./abis/WithdrawalManager.json
        - name: MapleGlobals
          file: ./abis/MapleGlobals.json
      eventHandlers:
        - event: WithdrawalProcessed(indexed address,uint256,uint256)
          handler: handleWithdrawalProcessed
      file: ./protocols/maple-finance-v2/src/mapping.ts
  # - kind: ethereum/contract
  #   name: LoanManager
  #   network: {{ network }}
  #   source:
  #     abi: LoanManager
  #   mapping:
  #     kind: ethereum/events
  #     apiVersion: 0.0.7
  #     language: wasm/assemblyscript
  #     entities: []
  #     abis:
  #       - name: LoanManager
  #         file: ./abis/LoanManager.json
  #       - name: MapleGlobals
  #         file: ./abis/MapleGlobals.json
  #     eventHandlers:
  #     file: ./protocols/maple-finance-v2/src/mapping.ts
  - kind: ethereum/contract
    name: Liquidator
    network: {{ network }}
    source:
      abi: Liquidator
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities: []
      abis:
        - name: Liquidator
          file: ./abis/Liquidator.json
        - name: MapleGlobals
          file: ./abis/MapleGlobals.json
      eventHandlers:
        - event: PortionLiquidated(uint256,uint256)
          handler: handlePortionLiquidated
      file: ./protocols/maple-finance-v2/src/mapping.ts